services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: https://www.valenceapchem.com
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
